project_id = "ccgvldazqlyvptschjkl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
s3_max_part_size = "5MiB"

[auth]
enabled = true
port = 54325
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false
enable_phone_signup = false

[functions.generate-invoice]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54326
inspector_port = 5555