// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccgvldazqlyvptschjkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZ3ZsZGF6cWx5dnB0c2NoamtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzU5NTcsImV4cCI6MjA3Mjc1MTk1N30.kOkfaA5VPFbcDTFv2ox6NBRz1OuiJWDSYb7x967QMEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});